[project]
name = "flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "elasticsearch>=9.2.1",
    "youtube-transcript-api>=1.2.3",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
